---
fail_fast: false
exclude: >
      (?x)(
          \\.dist-info |
          build |
          notebooks
      )
repos:
#  - repo: local
#    hooks:
#      - id: pipenv-setup-check
#        name: pipenv-setup-check
#        entry: env SETUPTOOLS_USE_DISTUTILS=stdlib pipenv run pipenv-setup sync
#        language: system
#        files: ^setup\.py|Pipfile|Pipfile\.lock$
#        pass_filenames: false
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--filter-files]
        files: \.py$
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json
      - id: mixed-line-ending
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==22.1.11]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-d=relaxed]
#  - repo: local
#    hooks:
#      - id: mypy-env
#        name: mypy-env
#        entry: ./scripts/env_runner.py mypy
#        language: system
#        types: [python]
#        args:
#          - --show-traceback
