raw_data_path: data/raw/
processed_data_path: data/processed/
remote_processed_path: s3://reproml-data/processed/

lyrics:
  name: lyrics
  path: "@format {this.lyrics.name}/"
  url: 'https://raw.githubusercontent.com/tmthyjames/cypher/master/data/lyrics_whole.csv.zip'
  partition_cols: [year]
  file_name: lyrics_whole.csv
